name: Buddies
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #for iOS cupertino icons
  cupertino_icons: ^1.0.0
  #for firebase core
  firebase_core: ^0.5.3
  #for google_sign_in
  google_sign_in: ^4.5.6
  #for firebase_auth
  firebase_auth: ^0.18.4+1
  #for firebase_messaging
  firebase_messaging: ^7.0.3
  #for firebase_storage
  firebase_storage: ^5.2.0
  #for cloud_firestore
  cloud_firestore: ^0.14.4
  #for image
  image: ^2.1.19
  #for animator
  animator: ^2.0.2
  #for image_picker
  image_picker: ^0.6.7+17
  #for timeago
  timeago: ^2.0.29
  #for cached_network_image
  cached_network_image: ^2.5.0
  #for geolocator
  geolocator: ^6.1.13
  #for uuid
  uuid: ^2.2.2
  #for path_provider
  path_provider: ^1.6.24
  #for flutter_svg
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
